package rpc

import (
	solana "github.com/fluxrpc/solana-go"
)

// ReturnData is the most-recent return data generated by an instruction in
// the transaction.
type ReturnData struct {
	ProgramId solana.PublicKey `json:"programId"`
	Data      solana.Data      `json:"data"`
}
