package rpc

import (
	solana "github.com/fluxrpc/solana-go"
)

// SimulateTransactionResponse is the response of the simulateTransaction
// method.
type SimulateTransactionResponse struct {
	RPCContext
	Value *SimulateTransactionResult `json:"value"`
}

// SimulateTransactionResult is the outcome of a simulated transaction.
type SimulateTransactionResult struct {
	// Error if transaction failed, null if transaction succeeded.
	Err any `json:"err,omitempty"`

	// Array of log messages the transaction instructions output during execution,
	// null if simulation failed before the transaction was able to execute
	// (for example due to an invalid blockhash or signature verification failure)
	Logs []string `json:"logs,omitempty"`

	// Array of accounts with the same length as the accounts.addresses array in the request.
	Accounts []*Account `json:"accounts"`

	// The number of compute budget units consumed during the processing of this transaction.
	UnitsConsumed *uint64 `json:"unitsConsumed,omitempty"`

	// The size of loaded accounts data in bytes.
	LoadedAccountsDataSize *uint32 `json:"loadedAccountsDataSize,omitempty"`

	// The most-recent return data generated by an instruction in the transaction.
	ReturnData *ReturnData `json:"returnData,omitempty"`

	// If innerInstructions were requested, a list of inner instructions.
	InnerInstructions []ParsedInnerInstruction `json:"innerInstructions,omitempty"`

	// The replacement blockhash used when replaceRecentBlockhash is true.
	ReplacementBlockhash *ReplacementBlockhash `json:"replacementBlockhash,omitempty"`

	// Fee this transaction was charged.
	Fee *uint64 `json:"fee,omitempty"`

	// Array of u64 account balances from before the transaction was processed.
	PreBalances []uint64 `json:"preBalances,omitempty"`

	// Array of u64 account balances after the transaction was processed.
	PostBalances []uint64 `json:"postBalances,omitempty"`

	// List of token balances from before the transaction was processed.
	PreTokenBalances []TokenBalance `json:"preTokenBalances,omitempty"`

	// List of token balances from after the transaction was processed.
	PostTokenBalances []TokenBalance `json:"postTokenBalances,omitempty"`

	// Addresses loaded from address lookup tables.
	LoadedAddresses *LoadedAddresses `json:"loadedAddresses,omitempty"`
}

// ReplacementBlockhash is the blockhash used to simulate the transaction when
// replaceRecentBlockhash is true.
type ReplacementBlockhash struct {
	Blockhash            solana.Hash `json:"blockhash"`
	LastValidBlockHeight uint64      `json:"lastValidBlockHeight"`
}

// SimulateTransactionOpts is the optional configuration object for the
// simulateTransaction method.
type SimulateTransactionOpts struct {
	// If true the transaction signatures will be verified
	// (default: false, conflicts with ReplaceRecentBlockhash)
	SigVerify bool `json:"sigVerify,omitempty"`

	// Commitment level to simulate the transaction at.
	// (default: "finalized").
	Commitment CommitmentType `json:"commitment,omitempty"`

	// If true the transaction recent blockhash will be replaced with the most recent blockhash.
	// (default: false, conflicts with SigVerify)
	ReplaceRecentBlockhash bool `json:"replaceRecentBlockhash,omitempty"`

	// If true the response will include inner instructions.
	// These inner instructions will be jsonParsed where possible,
	// otherwise json. (default: false)
	InnerInstructions bool `json:"innerInstructions,omitempty"`

	// The minimum slot that the request can be evaluated at.
	MinContextSlot *uint64 `json:"minContextSlot,omitempty"`

	Accounts *SimulateTransactionAccountsOpts `json:"accounts,omitempty"`
}

// SimulateTransactionAccountsOpts selects which accounts (and in which
// encoding) a simulateTransaction response should return.
type SimulateTransactionAccountsOpts struct {
	// (optional) Encoding for returned Account data,
	// either "base64" (default), "base64+zstd" or "jsonParsed".
	// - "jsonParsed" encoding attempts to use program-specific state parsers
	//   to return more human-readable and explicit account state data.
	//   If "jsonParsed" is requested but a parser cannot be found,
	//   the field falls back to binary encoding, detectable when
	//   the data field is type <string>.
	Encoding solana.EncodingType `json:"encoding,omitempty"`

	// An array of accounts to return.
	Addresses []solana.PublicKey `json:"addresses,omitempty"`
}
