package tokenmetadata

const (
	CreateMetadataAccountInstruction InstructionType = iota
	UpdateMetadataAccountInstruction
	DeprecatedCreateMasterEditionInstruction
	DeprecatedMintNewEditionFromMasterEditionViaPrintingTokenInstruction
	UpdatePrimarySaleHappenedViaTokenInstruction
	DeprecatedSetReservationListInstruction
	DeprecatedCreateReservationListInstruction
	SignMetadataInstruction
	DeprecatedMintPrintingTokensViaTokenInstruction
	DeprecatedMintPrintingTokensInstruction
	CreateMasterEditionInstruction
	MintNewEditionFromMasterEditionViaTokenInstruction
	ConvertMasterEditionV1ToV2Instruction
	MintNewEditionFromMasterEditionViaVaultProxyInstruction
	PuffMetadataInstruction
	UpdateMetadataAccountV2Instruction
	CreateMetadataAccountV2Instruction
	CreateMasterEditionV3Instruction
	VerifyCollectionInstruction
	UtilizeInstruction
	ApproveUseAuthorityInstruction
	RevokeUseAuthorityInstruction
	UnverifyCollectionInstruction
	ApproveCollectionAuthorityInstruction
	RevokeCollectionAuthorityInstruction
)
